name: mymath
author: lishude <lishude@foxmail.com>
version: 0.0.1
description: >
  This is a simple math package for learning Dart.

environment:
  sdk: ">=2.3.0 <3.0.0"

dev_dependencies:
  test: ^1.3.0
